--- Iniciando procesamiento ---
F
======================================================================
FAIL: test_process_all_files_structure_and_calculations (__main__.TestCSVProcessor.test_process_all_files_structure_and_calculations)
Prueba la función orquestadora `process_all_files`, verificando tanto
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/gerardomayor/Documents/estru_techos/apu_filter/test_app.py", line 79, in test_process_all_files_structure_and_calculations
    self.assertNotIn("error", resultado)
AssertionError: 'error' unexpectedly found in {'error': 'Uno o más archivos no pudieron ser procesados.'}

----------------------------------------------------------------------
Ran 1 test in 0.117s

FAILED (failures=1)